"""Branch operations domain models."""

from __future__ import annotations

from datetime import date, datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class BranchAlertSeverity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class BranchKPI(BaseModel):
    """Daily or intraday branch performance snapshot."""

    kpi_id: str
    branch_id: str
    branch_name: str | None = None
    region: str | None = None
    report_date: date
    report_type: str = "daily"  # daily | intraday
    # Service metrics
    avg_wait_time_minutes: float | None = None
    customer_satisfaction_score: float | None = None
    complaint_count: int = 0
    # Sales metrics
    new_accounts_opened: int = 0
    products_sold: int = 0
    referrals_generated: int = 0
    # Staffing
    scheduled_staff: int = 0
    actual_staff: int = 0
    # Transaction volume
    teller_transactions: int = 0
    atm_transactions: int = 0
    fraud_flagged_transactions: int = 0
    recorded_at: datetime = Field(default_factory=datetime.utcnow)


class BranchAlert(BaseModel):
    """Anomaly alert generated by the Branch Agent."""

    alert_id: str
    branch_id: str
    severity: BranchAlertSeverity
    anomaly_type: (
        str  # sales_decline | wait_time_spike | complaint_surge | staffing_gap | fraud_cluster
    )
    description: str
    kpi_snapshot_id: str | None = None
    period: str | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        use_enum_values = True


class BranchInsight(BaseModel):
    """AI-generated root-cause analysis and recommended actions for a branch."""

    insight_id: str
    branch_id: str
    trigger_alert_ids: list[str] = Field(default_factory=list)
    issue_summary: str
    probable_causes: list[str] = Field(default_factory=list)
    ranked_recommendations: list[str] = Field(default_factory=list)
    supporting_signals: dict = Field(default_factory=dict)
    manager_id: str | None = None
    manager_review_status: str = "pending"
    created_at: datetime = Field(default_factory=datetime.utcnow)
