/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as IndexRouteImport } from './routes/index'

const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/branches': typeof BranchesRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/loans': typeof LoansRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/branches': typeof BranchesRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/loans': typeof LoansRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/branches': typeof BranchesRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/loans': typeof LoansRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisory'
    | '/branches'
    | '/chat'
    | '/fraud'
    | '/loans'
    | '/sentiment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/branches'
    | '/chat'
    | '/fraud'
    | '/loans'
    | '/sentiment'
  id:
    | '__root__'
    | '/'
    | '/advisory'
    | '/branches'
    | '/chat'
    | '/fraud'
    | '/loans'
    | '/sentiment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoryRoute: typeof AdvisoryRoute
  BranchesRoute: typeof BranchesRoute
  ChatRoute: typeof ChatRoute
  FraudRoute: typeof FraudRoute
  LoansRoute: typeof LoansRoute
  SentimentRoute: typeof SentimentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoryRoute: AdvisoryRoute,
  BranchesRoute: BranchesRoute,
  ChatRoute: ChatRoute,
  FraudRoute: FraudRoute,
  LoansRoute: LoansRoute,
  SentimentRoute: SentimentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
